### ISSUE TITLE
Needs Clarification: A relative URL is supposed to work in index section?

### ISSUE THREAD

**Issue by hayatoito** [wpack-wg/bundled-responses#14]
The context is https://github.com/WICG/webpackage/issues/647

The current format says:

https://wpack-wg.github.io/bundled-responses/draft-ietf-wpack-bundled-responses.html#section-2.2-1

>  Representations within a bundle are named by their Content-Location (Section 8.7 of [I-D.ietf-httpbis-semantics]), which holds a URL. This is also known as the representation's URL.

https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-semantics-18#section-8.7
>     Content-Location = absolute-URI / partial-URI
 
Given that, it seems the format already allows a *relative URL* in the index section, however, it'd be better to ask a clarification than guessing its intention.

Using a relative URL is supposed to work? If so, we don't need to request a bundle format change to resolve https://github.com/WICG/webpackage/issues/647.

**Comment by horo-t** [comment]
More context: https://chromium-review.googlesource.com/c/chromium/src/+/3150318/3#message-58a152c5f290f8513abd3615ad24a4567626e3ba

This CL is intended to support relative URLs in web bundles for Subrerouce Web Bundle feature.

**Comment by horo-t** [comment]
@jyasskin What do you think about this?
I think the `Naming a representation` section was introduced by this change in WICG/webpackage.
https://github.com/WICG/webpackage/commit/826cadfa986bdb403bca2e149016459172f98144

**Comment by hayatoito** [comment]
cc: @felipeerias @littledan

**Comment by jyasskin** [comment]
We need to specify how the keys in the index section are parsed, independent of their semantics as `Content-Location`s. I'd intended that to eventually move to the [browser-side loading spec](https://wicg.github.io/webpackage/loading.html) when I removed the algorithms in #604, with the format spec here being less precise, but I think it was a mistake that I didn't even specify between absolute and relative URLs in the index. We should probably add a sentence here to say which it is. Since we have a use case for relative URLs, let's pick that one.

This spec should say something about what the URLs are relative to. Probably a bundle-defined base URL, which defaults to the location of the bundle but can be overridden by a section's contents? And that it's an error if two sections independently set the base URL without their own definitions disambiguating?

**Comment by horo-t** [comment]
I agree that the spec should clearly say that it supports relative URL.
Created [a PR](https://github.com/wpack-wg/bundled-responses/pull/15). Could you please reivew?

I think when we introduce a new `base` section, the `base` section should be able to override the bundle's URL. But I don't know how useful it is yet.

**Comment by felipeerias** [comment]
This is a good idea, thank you (and apologies for the delay in providing feedback). I have added a small suggestion [in the PR](https://github.com/wpack-wg/bundled-responses/pull/15#pullrequestreview-755762923).
